# Generated by Django 5.2.8 on 2025-11-18 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('created_ed', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SUPPLIER',
                'verbose_name_plural': 'SUPPLIERS',
                'ordering': ['-created_ed'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'CATEGORY', 'verbose_name_plural': 'CATEGORIES'},
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('created_ed', models.DateTimeField(auto_now_add=True)),
                ('updated_ed', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category')),
            ],
            options={
                'verbose_name': 'PRODUCT',
                'verbose_name_plural': 'PRODUCTS',
                'ordering': ['-created_ed'],
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
